@baseUrl = http://localhost:3000
@playerId = 6865b8210b9eca54c6b2243b
@categoryId = 6865f49083aa8aab5fd79559

### Get All players
GET {{baseUrl}}/player

### Get player by id
GET {{baseUrl}}/player/{{playerId}}

### Create player
POST {{baseUrl}}/player
Content-Type: application/json

{
  "name": "jogador 2",
  "email": "novo@jogador.com",
  "phoneNumber": "1234567890"
}

### Update player
PUT {{baseUrl}}/player/{{playerId}}
Content-Type: application/json

{
  "name": "Novo Nome do Jogador 32",
  "email": "novo@jogador.com"
}

### Delete player
DELETE {{baseUrl}}/player/{{playerId}}





### Get All categories
GET {{baseUrl}}/category

### Get category by id
GET {{baseUrl}}/category/{{categoryId}}

### Create category
POST {{baseUrl}}/category
Content-Type: application/json

{
  "name": "Categoria 2",
  "description": "Descrição da categoria 2",
  
  "events": [
    {
      "name": "Evento 2",
      "operation": "ADD",
      "value": 10	
    }
  ]
}

### Update category
PUT {{baseUrl}}/category/{{categoryId}}
Content-Type: application/json

{
  "description": "Descrição da categoria 2",
  "events": [
    {
      "name": "Evento 2",
      "operation": "ADD",
      "value": 10
    }
  ]
}

### Add player to category
POST {{baseUrl}}/category/{{categoryId}}/player/{{playerId}}